server:
  port: 9527
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: message-service-routh
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
          filters:
            - StripPrefix=1
        - id: monitor-service-routh
          uri: lb://monitor-service
          predicates:
            - Path=/monitor-service/**
          filters:
            - StripPrefix=1
        - id: pk-service-routh
          uri: lb://pk-service
          predicates:
            - Path=/pk-service/**
          filters:
            - StripPrefix=1
        - id: store-service-routh
          uri: lb://store-service
          predicates:
            - Path=/store-service/**
          filters:
            - StripPrefix=1
        - id: transaction-service-routh
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/**
          filters:
            - StripPrefix=1
        - id: user-service-routh
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: oauth-service-routh
          uri: lb://oauth-service
          predicates:
            - Path=/oauth-service/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
#          public-key-location: http://localhost:10007/rsa/publicKey
          jwk-set-uri: http://localhost:9527/oauth-service/rsa/publicKey #配置RSA的公钥访问地址
          public-key-location: jwt.jks

