server:
  port: 10005
spring:
  application:
    name: transaction-service
  jackson:
    # 日期格式（可根据自己的需求修改格式）
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      # 将数值类型转换为字符串，解决long型精度丢失
      write_numbers_as_strings: true

  datasource:
    url: jdbc:mysql://rm-bp17bfp26q7z51r10wo.mysql.rds.aliyuncs.com:3306/bugu_transaction_service?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root_bugu
    password: Pengyuyan520!
    type: com.alibaba.druid.pool.DruidDataSource   #配置阿里巴巴的Druid数据源
