server:
  port: 10001
spring:
  application:
    name: message-service
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: thomas10011-image
        calllback-url: http://88.88.88.88:12345
      access-key: LTAI4G4FGT6RrRPkDDPFW1Rw
      secret-key: SqP6v8fV5Uc60LGZOzbva3lP4itZSS
  datasource:
    url: jdbc:mysql://rm-bp17bfp26q7z51r10wo.mysql.rds.aliyuncs.com:3306/bugu_message_service?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root_bugu
    password: Pengyuyan520!
    type: com.alibaba.druid.pool.DruidDataSource   #配置阿里巴巴的Druid数据源
  mvc:
    throw-exception-if-no-handler-found: true
    # 不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
