server:
  port: 10001
spring:
  application:
    name: message-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
    # 不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
